
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 5;
  public static final int POR = 18;
  public static final int CHAR = 34;
  public static final int INT = 33;
  public static final int FOR = 10;
  public static final int CP = 4;
  public static final int NOT = 24;
  public static final int MENORIGUAL = 22;
  public static final int AND = 27;
  public static final int IGUAL = 14;
  public static final int CASTCHAR = 30;
  public static final int OR = 28;
  public static final int DIV = 17;
  public static final int NUM = 37;
  public static final int CC = 6;
  public static final int IF = 2;
  public static final int MAYORIGUAL = 23;
  public static final int EOF = 0;
  public static final int ASIG = 19;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int DIF = 13;
  public static final int MENOS = 16;
  public static final int MENOR = 21;
  public static final int IDENT = 36;
  public static final int MENOSUNARIO = 40;
  public static final int CLL = 26;
  public static final int REAL = 38;
  public static final int MAYOR = 20;
  public static final int CASTINT = 31;
  public static final int ELSE = 7;
  public static final int WHILE = 8;
  public static final int FLOAT = 35;
  public static final int ALL = 25;
  public static final int ASCII = 39;
  public static final int AP = 3;
  public static final int PRINT = 12;
  public static final int DO = 9;
  public static final int CASTFLOAT = 32;
  public static final int PYC = 11;
  public static final int MAS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "AP",
  "CP",
  "AC",
  "CC",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PYC",
  "PRINT",
  "DIF",
  "IGUAL",
  "MAS",
  "MENOS",
  "DIV",
  "POR",
  "ASIG",
  "MAYOR",
  "MENOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "NOT",
  "ALL",
  "CLL",
  "AND",
  "OR",
  "COMA",
  "CASTCHAR",
  "CASTINT",
  "CASTFLOAT",
  "INT",
  "CHAR",
  "FLOAT",
  "IDENT",
  "NUM",
  "REAL",
  "ASCII",
  "MENOSUNARIO"
  };
}

